---
apiVersion: v1
kind: Service
metadata:
  name: readarr
spec:
  type: NodePort
  selector:
    app: readarr
  ports:
    - name: http
      port: 8787
      protocol: TCP
      targetPort: 8787  
  externalIPs:
    - 192.168.0.211
    - 192.168.0.221
    - 192.168.0.222 
    - 192.168.0.223